# Generated by Django 5.1.5 on 2025-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.PositiveIntegerField()),
            ],
        ),
    ]
