# Generated by Django 5.1.7 on 2025-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_namegenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tree',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
